[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyearthtools"
readme = "README.md"
requires-python = ">=3.11, <3.14"
keywords = ["pyearthtools"]
maintainers = [
    { name = "Tennessee Leeuwenburg", email = "tennessee.leeuwenburg@bom.gov.au" },
]
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    # In future add "Programming Language :: Python :: 3.14" once our deps allow it
]

description = """\
PyEarthTools: Machine learning for Earth system science.
"""

version = "0.6.3"

dependencies = [
"pyearthtools-utils>=0.6.3",
"pyearthtools-data>=0.6.3",
"pyearthtools-pipeline>=0.6.3",
"pyearthtools-training>=0.6.3",
"pyearthtools-zoo>=0.6.3",
]

[project.optional-dependencies]
utils = [
    "pyearthtools-utils>=0.6.3",
]
data = [
    "pyearthtools-data>=0.6.3",
]
pipeline = [
    "pyearthtools-pipeline>=0.6.3",
]
training = [
    "pyearthtools-training>=0.6.3",
]
zoo = [
    "pyearthtools-zoo>=0.6.3",
]
all = [
    "pyearthtools-utils>=0.6.3",
    "pyearthtools-data[all]>=0.6.3",
    "pyearthtools-pipeline[all]>=0.6.3",
    "pyearthtools-training[all]>=0.6.3",
    "pyearthtools-zoo>=0.6.3",
]
test = ["pytest", "pytest-cov", "pytest-xdist"]
dev = ["pre-commit", "black==26.3.1", "ruff", "pudb"]
docs = [
    "sphinx",
    "myst-parser",
    "sphinx-book-theme",
    "scores",
    "xarray",
    "pandas",
    "scipy",
    "bottleneck",
    "nbsphinx",
    "sphinx_gallery",
    "sphinx-design",
    "sphinx-togglebutton",
    "sphinxcontrib-mermaid"
]

[project.urls]
homepage = "https://pyearthtools.readthedocs.io/"
documentation = "https://pyearthtools.readthedocs.io/"
repository = "https://github.com/ACCESS-Community-Hub/PyEarthTools"

[tool.isort]
profile = "black"

[tool.black]
line-length = 120

[tool.mypy]
warn_return_any = true
warn_unused_configs = true

[tool.ruff]
exclude = ["packages/bundled_models", "notebooks", "packages/met_office_site_archive"]

[tool.hatch.build.targets.wheel]
bypass-selection = true

[tool.hatch.build.targets.sdist]
only-include = ["pyproject.toml", "README.md", "LICENSE"]

[tool.pytest.ini_options]
addopts = [
    '--cov-fail-under=40',
    '--cov-branch',
    '--cov-report=html',
    '--junitxml=report.xml',
    '-n 4',
]
markers = [
    "noci: marks tests to exclude from CI/CD (deselect with '-m \"not noci\"')",
    "slow: mark test as slow (deselect with '-m \"not slow\"')",
]
